services:
  - type: web
    name: neugen-ai-admin-portal
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    numInstances: 1